[build]
  command = "bun install --frozen-lockfile || bun install && bun run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/index.html"
